# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "Jack Torrance",
  "email": "torans@overlook.net",
  "avatar": "torrance.png",
  "userKind": "pro",
  "favoritesOffers": [],
  "password": "shining"
}

###

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Отправить изображение

POST http://localhost:5000/users/65e3294d799c63847c713344/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.jpg"
Content-Type: image/png

< D:\PROJECTS\979743-six-cities-6\markup\img\apartment-02.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
