# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "John Wick",
  "email": "j.wick@pisem.local",
  "avatar": "wick.png",
  "userKind": "pro",
  "favoritesOffers": [],
  "password": "john4444"
}

###

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "j.wick@pisem.local",
  "password": "john4444"
}

###

## Проверить токен

GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imoud2lja0BwaXNlbS5sb2NhbCIsIm5hbWUiOiJKb2huIFdpY2siLCJpZCI6IjY1ZWVmOGIxMjVmOGY4MjdhZDkzMWNmMiIsImlhdCI6MTcxMDE2MjIyOCwiZXhwIjoxNzEwMzM1MDI4fQ.WcSq2Yxgusn1y7VI5GGkfnzuHoz1Q-5O1hoIUrWEoDQ


###

## Отправить изображение

POST http://localhost:5000/users/65e3294d799c63847c713344/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.jpg"
Content-Type: image/png

< D:\PROJECTS\979743-six-cities-6\markup\img\apartment-02.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
